# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

#  Loading Files with Summary or Meta Data

Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled 'Data'.

In [101]:
import pandas as pd

In [102]:
# I have prior knowledge of the text file by inspecting as a text document

In [103]:
#Zipcode_Demos.csv
zips = pd.read_csv('./Data/Zipcode_Demos.csv')
zips.head(100)

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,COUNT MALE,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,PERCENT MALE,0.396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,COUNT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,PERCENT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,COUNT GENDER TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,PERCENT GENDER TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,COUNT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,PERCENT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,COUNT HISPANIC LATINO,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,PERCENT HISPANIC LATINO,0.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,COUNT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,PERCENT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,COUNT ASIAN NON HISPANIC,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,PERCENT ASIAN NON HISPANIC,0.437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,COUNT WHITE NON HISPANIC,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,PERCENT WHITE NON HISPANIC,0.036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,COUNT BLACK NON HISPANIC,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,PERCENT BLACK NON HISPANIC,0.181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,COUNT OTHER ETHNICITY,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,PERCENT OTHER ETHNICITY,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,COUNT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,PERCENT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,COUNT ETHNICITY TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,PERCENT ETHNICITY TOTAL,79.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,COUNT PERMANENT RESIDENT ALIEN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,PERCENT PERMANENT RESIDENT ALIEN,0.061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,COUNT US CITIZEN,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,PERCENT US CITIZEN,0.739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,COUNT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,PERCENT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36,COUNT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,PERCENT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,COUNT CITIZEN STATUS TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,PERCENT CITIZEN STATUS TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [104]:
# So looks like I can at least eliminate the first non-header row. So use skiprow
# Additionally, looks like the table is broken up into two, 
# with the second piece transposed and appended to the bottom

# Pseudocode Plan
# Import first table
#   Skip first row | only take the first two columns | transpose it
# Import the second table 
#   Think it looks ok for now
# Append table 1 and table 2 together
zips = pd.read_csv('./Data/Zipcode_Demos.csv'
                  ,skiprows = 1
                  ,nrows = 45
                  ,usecols = list(range(1,3))
                  )
zips.head(100)

                             Unnamed: 1          0
0                     JURISDICTION NAME  10005.800
1                    COUNT PARTICIPANTS      9.400
2                          COUNT FEMALE      4.800
3                        PERCENT FEMALE      0.404
4                            COUNT MALE      4.600
5                          PERCENT MALE      0.396
6                  COUNT GENDER UNKNOWN      0.000
7                PERCENT GENDER UNKNOWN      0.000
8                    COUNT GENDER TOTAL      9.400
9                  PERCENT GENDER TOTAL     80.000
10               COUNT PACIFIC ISLANDER      0.000
11             PERCENT PACIFIC ISLANDER      0.000
12                COUNT HISPANIC LATINO      2.000
13              PERCENT HISPANIC LATINO      0.105
14                COUNT AMERICAN INDIAN      0.000
15              PERCENT AMERICAN INDIAN      0.000
16             COUNT ASIAN NON HISPANIC      3.600
17           PERCENT ASIAN NON HISPANIC      0.437
18             COUNT WHITE NON HISPANIC      0.800
19           PERCENT WHITE NON HISPANIC      0.036
20             COUNT BLACK NON HISPANIC      2.600
21           PERCENT BLACK NON HISPANIC      0.181
22                COUNT OTHER ETHNICITY      0.400
23              PERCENT OTHER ETHNICITY      0.040
24              COUNT ETHNICITY UNKNOWN      0.000
25            PERCENT ETHNICITY UNKNOWN      0.000
26                COUNT ETHNICITY TOTAL      9.400
27              PERCENT ETHNICITY TOTAL     79.900
28       COUNT PERMANENT RESIDENT ALIEN      0.500
29     PERCENT PERMANENT RESIDENT ALIEN      0.061
30                     COUNT US CITIZEN      8.900
31                   PERCENT US CITIZEN      0.739
32           COUNT OTHER CITIZEN STATUS      0.000
33         PERCENT OTHER CITIZEN STATUS      0.000
34         COUNT CITIZEN STATUS UNKNOWN      0.000
35       PERCENT CITIZEN STATUS UNKNOWN      0.000
36           COUNT CITIZEN STATUS TOTAL      9.400
37         PERCENT CITIZEN STATUS TOTAL     80.000
38     COUNT RECEIVES PUBLIC ASSISTANCE      2.300
39   PERCENT RECEIVES PUBLIC ASSISTANCE      0.151
40    COUNT NRECEIVES PUBLIC ASSISTANCE      7.100
41  PERCENT NRECEIVES PUBLIC ASSISTANCE      0.649
42      COUNT PUBLIC ASSISTANCE UNKNOWN      0.000
43    PERCENT PUBLIC ASSISTANCE UNKNOWN      0.000
44        COUNT PUBLIC ASSISTANCE TOTAL      9.400

In [105]:
zips_pt_1 = zips.T.copy()
zips_pt_1.head()

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
Unnamed: 1,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,PERCENT CITIZEN STATUS UNKNOWN,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL
0,10005.8,9.4,4.8,0.404,4.6,0.396,0,0,9.4,80,...,0,9.4,80,2.3,0.151,7.1,0.649,0,0,9.4

In [106]:
# Need the header to be actually row 1 values
real_header = zips_pt_1.iloc[0]
real_header.head(10)

0         JURISDICTION NAME
1        COUNT PARTICIPANTS
2              COUNT FEMALE
3            PERCENT FEMALE
4                COUNT MALE
5              PERCENT MALE
6      COUNT GENDER UNKNOWN
7    PERCENT GENDER UNKNOWN
8        COUNT GENDER TOTAL
9      PERCENT GENDER TOTAL
Name: Unnamed: 1, dtype: object

In [107]:
# Create new df without the bad row 1
zips_pt_1 = zips_pt_1[1:]
zips_pt_1

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,10005.8,9.4,4.8,0.404,4.6,0.396,0,0,9.4,80,...,0,9.4,80,2.3,0.151,7.1,0.649,0,0,9.4

In [108]:
# replace headers
zips_pt_1 = zips_pt_1.rename( columns = real_header )

In [109]:
zips_pt_1

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,PERCENT CITIZEN STATUS UNKNOWN,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL
0,10005.8,9.4,4.8,0.404,4.6,0.396,0,0,9.4,80,...,0,9.4,80,2.3,0.151,7.1,0.649,0,0,9.4

In [110]:
# Import the second table 
#   Think it looks ok for now
# Append table 1 and table 2 together
zips_pt_2 = pd.read_csv('./Data/Zipcode_Demos.csv'
                  ,skiprows = 47
#                  ,nrows = 
                  ,usecols = list(range(1,47))
                  )
zips_pt_2

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,10001,44,22,0.50,22,0.50,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
1,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
2,10003,1,1,1.00,0,0.00,0,0,1,100,...,1,100,0,0.00,1,1.00,0,0,1,100
3,10004,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
4,10005,2,2,1.00,0,0.00,0,0,2,100,...,2,100,0,0.00,2,1.00,0,0,2,100
5,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0.00,6,1.00,0,0,6,100
6,10007,1,0,0.00,1,1.00,0,0,1,100,...,1,100,1,1.00,0,0.00,0,0,1,100
7,10009,2,0,0.00,2,1.00,0,0,2,100,...,2,100,0,0.00,2,1.00,0,0,2,100
8,10010,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
9,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0.00,3,1.00,0,0,3,100

In [111]:
header_1 = zips_pt_1.iloc[0]
len(header_1)
header_1

JURISDICTION NAME                      10005.8
COUNT PARTICIPANTS                         9.4
COUNT FEMALE                               4.8
PERCENT FEMALE                           0.404
COUNT MALE                                 4.6
PERCENT MALE                             0.396
COUNT GENDER UNKNOWN                         0
PERCENT GENDER UNKNOWN                       0
COUNT GENDER TOTAL                         9.4
PERCENT GENDER TOTAL                        80
COUNT PACIFIC ISLANDER                       0
PERCENT PACIFIC ISLANDER                     0
COUNT HISPANIC LATINO                        2
PERCENT HISPANIC LATINO                  0.105
COUNT AMERICAN INDIAN                        0
PERCENT AMERICAN INDIAN                      0
COUNT ASIAN NON HISPANIC                   3.6
PERCENT ASIAN NON HISPANIC               0.437
COUNT WHITE NON HISPANIC                   0.8
PERCENT WHITE NON HISPANIC               0.036
COUNT BLACK NON HISPANIC                   2.6
PERCENT BLACK NON HISPANIC               0.181
COUNT OTHER ETHNICITY                      0.4
PERCENT OTHER ETHNICITY                   0.04
COUNT ETHNICITY UNKNOWN                      0
PERCENT ETHNICITY UNKNOWN                    0
COUNT ETHNICITY TOTAL                      9.4
PERCENT ETHNICITY TOTAL                   79.9
COUNT PERMANENT RESIDENT ALIEN             0.5
PERCENT PERMANENT RESIDENT ALIEN         0.061
COUNT US CITIZEN                           8.9
PERCENT US CITIZEN                       0.739
COUNT OTHER CITIZEN STATUS                   0
PERCENT OTHER CITIZEN STATUS                 0
COUNT CITIZEN STATUS UNKNOWN                 0
PERCENT CITIZEN STATUS UNKNOWN               0
COUNT CITIZEN STATUS TOTAL                 9.4
PERCENT CITIZEN STATUS TOTAL                80
COUNT RECEIVES PUBLIC ASSISTANCE           2.3
PERCENT RECEIVES PUBLIC ASSISTANCE       0.151
COUNT NRECEIVES PUBLIC ASSISTANCE          7.1
PERCENT NRECEIVES PUBLIC ASSISTANCE      0.649
COUNT PUBLIC ASSISTANCE UNKNOWN              0
PERCENT PUBLIC ASSISTANCE UNKNOWN            0
COUNT PUBLIC ASSISTANCE TOTAL              9.4
Name: 0, dtype: object

In [112]:
header_2 = zips_pt_2.iloc[0]
len(header_2)
header_2

JURISDICTION NAME                      10001.00
COUNT PARTICIPANTS                        44.00
COUNT FEMALE                              22.00
PERCENT FEMALE                             0.50
COUNT MALE                                22.00
PERCENT MALE                               0.50
COUNT GENDER UNKNOWN                       0.00
PERCENT GENDER UNKNOWN                     0.00
COUNT GENDER TOTAL                        44.00
PERCENT GENDER TOTAL                     100.00
COUNT PACIFIC ISLANDER                     0.00
PERCENT PACIFIC ISLANDER                   0.00
COUNT HISPANIC LATINO                     16.00
PERCENT HISPANIC LATINO                    0.36
COUNT AMERICAN INDIAN                      0.00
PERCENT AMERICAN INDIAN                    0.00
COUNT ASIAN NON HISPANIC                   3.00
PERCENT ASIAN NON HISPANIC                 0.07
COUNT WHITE NON HISPANIC                   1.00
PERCENT WHITE NON HISPANIC                 0.02
COUNT BLACK NON HISPANIC                  21.00
PERCENT BLACK NON HISPANIC                 0.48
COUNT OTHER ETHNICITY                      3.00
PERCENT OTHER ETHNICITY                    0.07
COUNT ETHNICITY UNKNOWN                    0.00
PERCENT ETHNICITY UNKNOWN                  0.00
COUNT ETHNICITY TOTAL                     44.00
PERCENT ETHNICITY TOTAL                  100.00
COUNT PERMANENT RESIDENT ALIEN             2.00
PERCENT PERMANENT RESIDENT ALIEN           0.05
COUNT US CITIZEN                          42.00
PERCENT US CITIZEN                         0.95
COUNT OTHER CITIZEN STATUS                 0.00
PERCENT OTHER CITIZEN STATUS               0.00
COUNT CITIZEN STATUS UNKNOWN               0.00
PERCENT CITIZEN STATUS UNKNOWN             0.00
COUNT CITIZEN STATUS TOTAL                44.00
PERCENT CITIZEN STATUS TOTAL             100.00
COUNT RECEIVES PUBLIC ASSISTANCE          20.00
PERCENT RECEIVES PUBLIC ASSISTANCE         0.45
COUNT NRECEIVES PUBLIC ASSISTANCE         24.00
PERCENT NRECEIVES PUBLIC ASSISTANCE        0.55
COUNT PUBLIC ASSISTANCE UNKNOWN            0.00
PERCENT PUBLIC ASSISTANCE UNKNOWN          0.00
COUNT PUBLIC ASSISTANCE TOTAL             44.00
PERCENT PUBLIC ASSISTANCE TOTAL          100.00
Name: 0, dtype: float64

Looks like the missing column is `PERCENT PUBLIC ASSISTANCE TOTAL`, so will need to create in table 1

In [113]:
# On inspecting the rest of the data, this is just % of total. So if count > 0, should be 100%
zips_pt_1['PERCENT PUBLIC ASSISTANCE TOTAL'] = 100.00
zips_pt_1

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,10005.8,9.4,4.8,0.404,4.6,0.396,0,0,9.4,80,...,9.4,80,2.3,0.151,7.1,0.649,0,0,9.4,100.0

In [114]:
zips_combined = zips_pt_1.append(zips_pt_2, sort = False)
zips_combined.head().T

                                           0      0      1      2      3
JURISDICTION NAME                    10005.8  10001  10002  10003  10004
COUNT PARTICIPANTS                       9.4     44     35      1      0
COUNT FEMALE                             4.8     22     19      1      0
PERCENT FEMALE                         0.404    0.5   0.54      1      0
COUNT MALE                               4.6     22     16      0      0
PERCENT MALE                           0.396    0.5   0.46      0      0
COUNT GENDER UNKNOWN                       0      0      0      0      0
PERCENT GENDER UNKNOWN                     0      0      0      0      0
COUNT GENDER TOTAL                       9.4     44     35      1      0
PERCENT GENDER TOTAL                      80    100    100    100      0
COUNT PACIFIC ISLANDER                     0      0      0      0      0
PERCENT PACIFIC ISLANDER                   0      0      0      0      0
COUNT HISPANIC LATINO                      2     16      1      0      0
PERCENT HISPANIC LATINO                0.105   0.36   0.03      0      0
COUNT AMERICAN INDIAN                      0      0      0      0      0
PERCENT AMERICAN INDIAN                    0      0      0      0      0
COUNT ASIAN NON HISPANIC                 3.6      3     28      1      0
PERCENT ASIAN NON HISPANIC             0.437   0.07    0.8      1      0
COUNT WHITE NON HISPANIC                 0.8      1      6      0      0
PERCENT WHITE NON HISPANIC             0.036   0.02   0.17      0      0
COUNT BLACK NON HISPANIC                 2.6     21      0      0      0
PERCENT BLACK NON HISPANIC             0.181   0.48      0      0      0
COUNT OTHER ETHNICITY                    0.4      3      0      0      0
PERCENT OTHER ETHNICITY                 0.04   0.07      0      0      0
COUNT ETHNICITY UNKNOWN                    0      0      0      0      0
PERCENT ETHNICITY UNKNOWN                  0      0      0      0      0
COUNT ETHNICITY TOTAL                    9.4     44     35      1      0
PERCENT ETHNICITY TOTAL                 79.9    100    100    100      0
COUNT PERMANENT RESIDENT ALIEN           0.5      2      2      0      0
PERCENT PERMANENT RESIDENT ALIEN       0.061   0.05   0.06      0      0
COUNT US CITIZEN                         8.9     42     33      1      0
PERCENT US CITIZEN                     0.739   0.95   0.94      1      0
COUNT OTHER CITIZEN STATUS                 0      0      0      0      0
PERCENT OTHER CITIZEN STATUS               0      0      0      0      0
COUNT CITIZEN STATUS UNKNOWN               0      0      0      0      0
PERCENT CITIZEN STATUS UNKNOWN             0      0      0      0      0
COUNT CITIZEN STATUS TOTAL               9.4     44     35      1      0
PERCENT CITIZEN STATUS TOTAL              80    100    100    100      0
COUNT RECEIVES PUBLIC ASSISTANCE         2.3     20      2      0      0
PERCENT RECEIVES PUBLIC ASSISTANCE     0.151   0.45   0.06      0      0
COUNT NRECEIVES PUBLIC ASSISTANCE        7.1     24     33      1      0
PERCENT NRECEIVES PUBLIC ASSISTANCE    0.649   0.55   0.94      1      0
COUNT PUBLIC ASSISTANCE UNKNOWN            0      0      0      0      0
PERCENT PUBLIC ASSISTANCE UNKNOWN          0      0      0      0      0
COUNT PUBLIC ASSISTANCE TOTAL            9.4     44     35      1      0
PERCENT PUBLIC ASSISTANCE TOTAL          100    100    100    100      0

Good enough. Some additional type scrubbing could be done, but will leave for now in interest of time.

## Level Up (Optional)

### Loading Corrupt CSV files

Occassionally, you encountered some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is suppossed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restuarant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restuarant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [ ]:
#Hint: here's a useful programming pattern to use.
try:
    #do something
except Exception as e:
    #handle your exception e

In [ ]:
#Your code here